#服务配置
server:
  port: 20000
  servlet:
    context-path: /

spring:
  application:
    name: activemq-consumer

  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin

#  activemq:
#    broker-url: tcp://dc.foyoedu.com:61616
#    user: app.test
#    password: 51bcde83c63b41e4bc20001c05d72653

queue: queue
#queue: Consumer.YUHUAN