#服务配置
server:
  port: 10000
  servlet:
    context-path: /

spring:
  application:
    name: spring-boot-gateway

  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: auth
          #          uri: lb://auth
          uri: http://127.0.0.1:10210
          predicates:
            - Path=/api/v1/**
            - Method=GET,POST,DELETE,PUT,OPTIONS
          filters:
            #            - AddRequestHeader=Access-Control-Allow-Origin,*
            #            - SetPath=/{segment}
            - RewritePath=/api/v1(?<segment>/?.*), $\{segment}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"